### ISSUE TITLE
It may make sense to upstream your specs into https://github.com/kaitai-io/kaitai_struct_formats/

### ISSUE THREAD

**Issue by KOLANICH** [trejkaz/modelling_formats#1]

**Comment by hakanai** [comment]
I never really knew how that worked. I figured if they wanted them, they could merge.

**Comment by KOLANICH** [comment]
I feel like the upstreaming is better to be done by the author lf the specs rather than by a third party. The author understands own specs and how they interact to other code better.

**Comment by hakanai** [comment]
[Pull requested](https://github.com/kaitai-io/kaitai_struct_formats/pull/420)
